### ISSUE TITLE
React Support

### ISSUE THREAD

**Issue by razznblue** [ailon/piano-chart#14]
Hello There! Thank you for building such a useful tool!
I am considering using this library for an upcoming project of mine. 
My question is does it support use with React or Next.js?

I plan on testing that later this week but figured I would ask here also 🤷 
Also I hope it is okay to ask this here 😅

**Comment by ailon** [comment]
While there's nothing special for React in it, I don't see a reason why it wouldn't work. [PianoShow.me](https://pianoshow.me/) uses it with Vue, so it should be fine with React as well.
